name: waresys_fix1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Sedikit menaikkan batas bawah untuk kompatibilitas yang lebih baik

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (versi terbaru yang stabil)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_database: ^10.4.9
  firebase_messaging: ^14.7.19
  # firebase_ml_model_downloader sudah deprecated, pertimbangkan alternatif seperti tflite_flutter_helper
  # Jika tetap dibutuhkan, versi terakhirnya adalah 0.2.0+1, namun mungkin tidak kompatibel
  # firebase_ml_model_downloader: ^0.2.0+1

  # Auth providers
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # State management & utils
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_storage: ^2.1.1

  # UI & Animations
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  photo_view: ^0.15.0
  video_player: ^2.8.3
  chewie: ^1.7.5

  # Device & native features
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  share_plus: ^7.2.2
  webview_flutter: ^4.7.0
  local_auth: ^2.2.0
  # biometric_storage: ^5.0.0+4 (versi ini terlihat baik, kita pertahankan)
  biometric_storage: ^5.0.0+4

  # Background & downloads
  flutter_background_service: ^5.0.5
  # flutter_downloader tidak lagi di-maintain. Pertimbangkan flutter_downloader_plus atau workmanager
  # flutter_downloader: ^1.11.6

  # File handling
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  pdf: ^3.10.8
  archive: ^3.4.10
  flutter_archive: ^6.0.0
  csv: ^5.1.1
  xml: ^6.5.0
  yaml: ^3.1.2

  # Audio
  audioplayers: ^6.0.0
  just_audio: ^0.9.36

  # QR & barcode
  qr_flutter: ^4.1.0
  # barcode_scan2 tidak di-maintain, ganti dengan mobile_scanner
  mobile_scanner: ^4.0.1

  # AI & ML
  tflite_flutter: ^0.11.0
  collection: ^1.18.0
  # Paket ML dari DartML tampaknya sudah lama, pertimbangkan alternatif yang lebih baru jika ada masalah
  ml_algo: ^16.18.0
  ml_dataframe: ^1.6.0
  ml_preprocessing: ^7.0.0

  # Other utils
  intl: ^0.19.0
  uuid: ^4.4.0
  rxdart: ^0.27.7
  logger: ^2.2.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  app_tracking_transparency: ^2.0.4
  rate_my_app: ^2.0.0
  store_redirect: ^2.0.1
  excel: ^4.0.6

  # News service dependencies
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  # freezed: ^3.2.0 (versi ini terlalu tinggi dan mungkin salah ketik)
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1 # Tambahkan ini untuk freezed
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  mobx_codegen: ^2.6.0
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  fake_cloud_firestore: ^2.5.0
  firebase_auth_mocks: ^0.13.0
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  # alchemist: ^0.12.1 (pertahankan jika tidak ada konflik)
  alchemist: ^0.12.1
  patrol: ^3.5.1
  integration_test:
    sdk: flutter

dependency_overrides:
  # Hapus override jika tidak benar-benar dibutuhkan
  # FFI dan collection biasanya tidak perlu di-override kecuali ada konflik spesifik
  # ffi: ^2.1.2
  # collection: ^1.18.0
  meta: ^1.11.0 # Override ini sering dibutuhkan untuk resolver

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google.svg
    - assets/apple.svg
    - assets/warehouse_bg.jpg
    - assets/fonts/
    - assets/ml/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf