// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdiCtUFRLyo_aOCQ7EthMkzxeoBKNjq5M',
    appId: '1:323480284287:web:your_web_app_id',
    messagingSenderId: '323480284287',
    projectId: 'waresysv2',
    authDomain: 'waresysv2.firebaseapp.com',
    storageBucket: 'waresysv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdiCtUFRLyo_aOCQ7EthMkzxeoBKNjq5M',
    appId: '1:323480284287:android:3a3f3c9632456a9698a34a',
    messagingSenderId: '323480284287',
    projectId: 'waresysv2',
    storageBucket: 'waresysv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa50ZI87-wjBGOimQX7Am4HXstfVxIo00',
    appId: '1:323480284287:ios:your_ios_app_id',
    messagingSenderId: '323480284287',
    projectId: 'waresysv2',
    storageBucket: 'waresysv2.firebasestorage.app',
    iosBundleId: 'com.waresys.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa50ZI87-wjBGOimQX7Am4HXstfVxIo00',
    appId: '1:323480284287:ios:your_ios_app_id',
    messagingSenderId: '323480284287',
    projectId: 'waresysv2',
    storageBucket: 'waresysv2.firebasestorage.app',
    iosBundleId: 'com.waresys.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdiCtUFRLyo_aOCQ7EthMkzxeoBKNjq5M',
    appId: '1:323480284287:web:your_web_app_id',
    messagingSenderId: '323480284287',
    projectId: 'waresysv2',
    authDomain: 'waresysv2.firebaseapp.com',
    storageBucket: 'waresysv2.firebasestorage.app',
  );
}