import 'package:firebase_auth/firebase_auth.dart';
import '../models/hrm/employee_model.dart';
import '../services/hrm/employee_repository.dart';

class EmployeeSeeder {
  static final EmployeeRepository _employeeRepository = EmployeeRepository();

  /// Create employee data for current logged-in user if not exists
  static Future<String?> createEmployeeForCurrentUser() async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        print('❌ No user logged in');
        return null;
      }

      // Check if employee already exists
      final existingEmployee = await _employeeRepository.getByUserId(user.uid);
      if (existingEmployee != null) {
        print('✅ Employee already exists: ${existingEmployee.employeeId}');
        return existingEmployee.employeeId;
      }

      // Create new employee
      final employee = EmployeeModel(
        employeeId: '', // Will be auto-generated by Firestore
        userId: user.uid,
        fullName: user.displayName ?? user.email?.split('@').first ?? 'User',
        position: 'Employee',
        department: 'General',
        joinDate: DateTime.now(),
        salary: 5000000, // Default salary
        status: EmployeeStatus.active,
        role: EmployeeRole.employee,
        leaveBalance: 12,
      );

      final employeeId = await _employeeRepository.create(employee);
      print('✅ Created new employee: $employeeId for user: ${user.uid}');
      return employeeId;
    } catch (e) {
      print('❌ Error creating employee: $e');
      return null;
    }
  }

  /// Create multiple dummy employees for testing
  static Future<void> createDummyEmployees() async {
    try {
      final dummyEmployees = [
        EmployeeModel(
          employeeId: '',
          userId: 'dummy_user_1',
          fullName: 'John Doe',
          position: 'Software Developer',
          department: 'IT',
          joinDate: DateTime.now().subtract(const Duration(days: 365)),
          salary: 8000000,
          status: EmployeeStatus.active,
          role: EmployeeRole.employee,
          leaveBalance: 10,
        ),
        EmployeeModel(
          employeeId: '',
          userId: 'dummy_user_2',
          fullName: 'Jane Smith',
          position: 'HR Manager',
          department: 'Human Resources',
          joinDate: DateTime.now().subtract(const Duration(days: 730)),
          salary: 12000000,
          status: EmployeeStatus.active,
          role: EmployeeRole.manager,
          leaveBalance: 15,
        ),
        EmployeeModel(
          employeeId: '',
          userId: 'dummy_user_3',
          fullName: 'Bob Johnson',
          position: 'Warehouse Supervisor',
          department: 'Logistics',
          joinDate: DateTime.now().subtract(const Duration(days: 180)),
          salary: 6500000,
          status: EmployeeStatus.active,
          role: EmployeeRole.employee,
          leaveBalance: 12,
        ),
      ];

      for (final employee in dummyEmployees) {
        final employeeId = await _employeeRepository.create(employee);
        print('✅ Created dummy employee: $employeeId - ${employee.fullName}');
      }
    } catch (e) {
      print('❌ Error creating dummy employees: $e');
    }
  }
}